# Generated by Django 3.2.5 on 2023-05-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readings',
            old_name='reinfall',
            new_name='rainfall',
        ),
    ]
